### ISSUE TITLE
Why are you using my images?

### ISSUE THREAD

**Issue by vecalion** [jorgemht/Xamarin#1]
That's not cool :(
Original:
https://crossplatform.space/2015/11/mvvm-the-beauty-of-cross-platform-development/

Your: 
https://github.com/jorgemht/Xamarin/wiki/MVVM-pattern

**Comment by jorgemrht** [comment]
Hello Vecalion,

sorry for using your photo.

I just added you in my readme credits.

In my early days I wouldn't be as careful about these things when I started github as now. I will review my old repositories to update licenses.

If you still want me to delete the photo, I delete it.

Thanks for your comment

**Comment by vecalion** [comment]
Hey, 
thanks, I don't mind you using the images as long as you respect the ownership. I kinda love these images, they're hand-drawn by my wife :)

Kind regards,
Val
